@startuml
skinparam classAttributeIconSize 0
abstract Number {
+text: str
+number: int
+getNumber()
}
class InitialNumber {
+number: str
+getNumber()
}
class ChangedNumber {
+getNumber()
}
class NumberBase {
}
interface CommandsToDo {
+startFiltering()
}
class FilterMemory

class FilterByIndentRemoving {
+execute()
}
class FilterByDashRemoving {
+execute()
}
class TenSymbolsFromRight {
+execute()
}
class 1Adding {
+execute()
}

class IndentRemover {
+indentIdentifier()
+remover()
}

class DashRemover {
+dashIdentifier()
+remover()
}

class TSFR {
+right10Symbolscounting()
+removingLast()
}

class Generalize {
+countryCodeAdder()
}

InitialNumber -> CommandsToDo
NumberBase -|> Number
Number --|> InitialNumber
Number --|> ChangedNumber

CommandsToDo <|--- FilterByIndentRemoving
CommandsToDo <|-- FilterByDashRemoving
CommandsToDo <|-- TenSymbolsFromRight
CommandsToDo <|-- 1Adding

IndentRemover <-- FilterMemory
DashRemover <-- FilterMemory
TSFR <-- FilterMemory
Generalize <-- FilterMemory

FilterByIndentRemoving ..|> IndentRemover
FilterByDashRemoving ..|> DashRemover
TenSymbolsFromRight ..|> TSFR
1Adding ..|> Generalize

FilterByIndentRemoving <.. FilterMemory
FilterByDashRemoving <.. FilterMemory
TenSymbolsFromRight <.. FilterMemory
1Adding <.. FilterMemory

FilterMemory .|> ChangedNumber
@enduml


